### ISSUE TITLE
Update 

### ISSUE THREAD

**Issue by scamianbas** [shahariarrabby/deeplearning.ai#3]
Hi @shahariarrabby there's a "Residual Networks - v2.ipynb" on Coursera, can you please update this repository accordingly ? Thanks !

**Comment by ShahariarRabby** [comment]
You failed to load resnet model? 
Or can you mention where is the problem?

**Comment by scamianbas** [comment]
"Residual Networks - v1.ipynb" is not used anymore in Coursera and is replaced now by "Residual Networks - v2.ipynb" and I would like to start from a fresh notebook as I cannot undo all the edits I did (especially outside the ##PUT YOUR CODE HERE marks.

**Comment by ShahariarRabby** [comment]
Oh! Ok
Done 👍 
Btw, Thank you
